name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # If you use Next.js ESLint; otherwise use your linter cmd
      - name: Lint
        run: npm run lint --if-present || npx next lint

      # Type-checks the whole project without emitting files
      - name: Typecheck
        run: npx tsc --noEmit
