name: Policy

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  protect-critical-paths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fail if critical paths changed without approval label
        uses: actions/github-script@v7
        with:
          script: |
            const forbidden = [
              '^src/lib/supabase/.*',
              '^src/app/api/auth/.*',
              '^supabase/.*\\.sql$',
              '^src/lib/llm/openaiFetch\\.ts$',   // optional: lock core adapters if you want
            ];
            const requiresLabel = 'requires-owner-ok';

            const pr = context.payload.pull_request;
            const labels = (pr.labels || []).map(l => l.name);
            const hasOverride = labels.includes(requiresLabel);

            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              per_page: 200
            });

            const changed = files.map(f => f.filename);
            const bad = changed.filter(path => forbidden.some(re => new RegExp(re).test(path)));

            if (bad.length && !hasOverride) {
              core.setFailed(
                `Critical paths changed without '${requiresLabel}' label:\n` +
                bad.map(b => ' - ' + b).join('\n')
              );
            } else {
              core.info('Policy OK');
            }
